<?php

/**
 * @file
 * Contains session_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\session_manager\Event\SessionManagerUserLoginEvent;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function session_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the session_manager module.
    case 'help.page.session_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides UI for user session management') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_user_login().
 */
function session_manager_user_login(UserInterface $account) {
  // Instantiate user login event.
  $event = new SessionManagerUserLoginEvent($account);

  // Get the event_dispatcher server and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(SessionManagerUserLoginEvent::EVENT_NAME, $event);
}
